name: GitHub Profile Summary Cards

on:
  schedule:
    # Everyday at 00:00
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: profile-readme-update
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Generates a profile cards from a github user (<github_user_name>) profile
      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: kevinliddel
          BRANCH_NAME: "main"
          UTC_OFFSET: 3
          AUTO_PUSH: false

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync Profile Summary Cards"