name: snake animation

on:
  schedule:
    # Everyday at 00:00
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: profile-readme-update
  cancel-in-progress: false

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      
      # Generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake/github-contribution-grid-snake.svg
            assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Pull latest changes
        run: git pull --rebase --autostash origin main

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync Snake Animation with recent contributions"